name: "playslot_savi"
type: "playslot_savi"

resolution: [64, 64]
n_sample_frames: 16

num_slots: 4
slot_dim: 128
num_iterations_first: 3
num_iterations: 1
in_channels: 3
mlp_hidden: 256
mlp_encoder_dim: 128

initializer: "LearnedRandom"

transition_module_params:
  model_name: "TransformerBlock"
  num_heads: 4
  head_dim: 32
  mlp_size: 512

encoder:
  encoder_name: "ConvEncoder"
  encoder_params:
    num_channels: [32, 32, 32, 32]
    kernel_size: 5
    resolution: [64, 64]
    downsample_encoder: false
    downsample: 2

decoder:
  decoder_name: "ConvDecoder"
  decoder_params:
    num_channels: [64, 64, 64, 64]
    kernel_size: 5
    resolution: [64, 64]
    downsample_decoder: false
    upsample: 1

weight_dict:
  recon: 1.0
