defaults:
  - model: savi
  - dataset: pusht
  - loss: savi_default
  - optional experiment: null
  - _self_


exp_name: ${model.name}_${dataset.name}
seed: 42
epochs: 8
batch_size: 128
num_workers: 8
lr: 2e-4
weight_decay: 1e-4
grad_clip_norm: 1.0
scheduler: null

dry_run: false
max_steps: null
ckpt_path: null
use_amp: true
mode: deterministic
clips_per_ep: 2
device: cuda

